### ISSUE TITLE
Estudando Ecmascript 6

### ISSUE THREAD

**Issue by nbfontana** [unisul-opensource/repo-control#1]
> **Nome do repositório**: learning-es6
> **Descrição**: Learning the latest standardized version of JavaScript, ECMAScript 6, or ES6. 
> **Motivo (Informações extras)**: Um repositório contendo algoritmos escritos em es6, onde todos podem contribuir com informações novas sobre o ECMAScript.

**Comment by alexandredavi** [comment]
Repositório [learning-es6](https://github.com/unisul-opensource/learning-es6) criado.

`while (true) {
    keepCoding();
}`
