### ISSUE TITLE
Implementando Annyang

### ISSUE THREAD

**Issue by alexandredavi** [unisul-opensource/repo-control#2]
> **Nome do repositório**: annyang-speech-recognition
> **Descrição do repositório**: Exemplos simples de como utilizar a biblioteca JavaScript Annyang para executar funções via comando de voz.
> **Motivo (Informações extras)**: Discernir conhecimento sobre a biblioteca.

**Comment by nbfontana** [comment]
Repositório criado [annyang-speech-recognition](https://github.com/unisul-opensource/annyang-speech-recognition).
