### ISSUE TITLE
Jogo da velha - IA

### ISSUE THREAD

**Issue by nbfontana** [unisul-opensource/repo-control#4]
> **Nome do repositório**: tic-tac-toe
> **Descrição do repositório**: Jogo da Velha implementado em Java utilizando de técnicas de Inteligência Artificial para simular o oponente.
> **Motivo (Informações extras)**: Discernir conhecimento de IA

**Comment by alexandredavi** [comment]
Repositório criado: [tic-tac-toe](https://github.com/unisul-opensource/tic-tac-toe)
