### ISSUE TITLE
java-webservices-examples

### ISSUE THREAD

**Issue by alexandredavi** [unisul-opensource/repo-control#5]
> **Nome do repositório**: java-webservices-examples
> **Descrição do repositório**: Repositório para implementação de exemplos de web services SOAP e REST 
> **Motivo (Informações extras)**: Demonstrar de maneira simples como pode ser implementado web services em java

**Comment by nbfontana** [comment]
Repositório [java-webservices-examples](https://github.com/unisul-opensource/java-webservices-examples) criado.
